name: Test with Platformio

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Prepare
        run: |
          sudo apt update && sudo apt install -y valgrind
          python -m pip install --upgrade pip
          pip install platformio
          pio pkg install --global --library bblanchon/ArduinoJson@^7
      - name: Run test
        run: |
          pio test -e native -v
